# Generated by Django 4.2.3 on 2023-07-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
